#!/bin/bash

ARGS=$(echo "$1" | tr ":" "\n")

lscont=""; lssat="";
for o in $ARGS; do
	case "$o" in
		controller) lscont="true" ;;
		combined) lscont="true"; lssat="true" ;;
		satellite) lssat="true" ;;
	esac
done

export PATH=$PATH:/usr/share/linstor-server/bin

# Configure linstor to log to files
sed -i /usr/share/linstor-server/lib/conf/logback.xml \
	-e 's#<!-- <appender-ref ref="FILE" /> -->#<appender-ref ref="FILE" />#' \
	-e 's#level="INFO"#level="TRACE"#'

[ -z "$lscont" ] && [ -z "$lssat" ] && lssat="true"

if [ "$lscont" = "true" ]; then
	Controller -c /etc/linstor -l /var/log/linstor/controller &
fi

if [ "$lssat" = "true" ]; then
	Satellite -l /var/log/linstor/satellite &
fi
