#!/bin/sh

create_vg() {
	VGname=$1
	VGpath=$2

	if [ ! -f /.resume ]; then
		rm -f "$VGpath" # new file, so that it's no longer shared for sure.
		if [ ! -f "$VGpath"  ]; then
			truncate --size 1T "$VGpath"
		fi
	fi

	D=`losetup --find`
	losetup $D "$VGpath"
	udevadm settle -t 10 -E $D
	vgscan
	if ! vgs | grep "$VGname"; then
		pvcreate $D
		vgcreate $VGname $D --physicalextentsize=8k
	fi
	vgchange -ay
}

# create vg
# not in /tmp, because that is a limited-size tmpfs
[ "$LB_DIST" = "rhel6.0" ] && { modprobe dm-mod; sed -i "s/use_lvmetad/use_lvmetad=1 #/" /etc/lvm/lvm.conf; }
mkdir -p /run/lvm && /sbin/lvmetad
modprobe loop
create_vg scratch /var/lib/my-vg
