#!/bin/bash

blockdevice=""
ramdisk=""
thinpercent=""

ARGS=$(echo $1 | tr ":" "\n")
for o in $ARGS; do
	case "$o" in
		bd=*) blockdevice="true" ;;
		thinpercent=*) export $o ;;
		ramdisk=*) export $o ;;
	esac
done

create_vg() {
	VGname=$1
	VGpath=$2
	backing=$3

	if [ ! -f /.resume ] && [ "$backing" = "file" ]; then
		rm -f "$VGpath" # new file, so that it's no longer shared for sure.
		if [ ! -f "$VGpath"  ]; then
			truncate --size 1T "$VGpath"
		fi
	fi

	if [ "$backing" = "file" ]; then
		D=$(losetup --find)
		losetup "$D" "$VGpath"
	else
		D=$VGpath
	fi
	udevadm settle -t 10 -E "$D"
	vgscan
	if ! vgs | grep "$VGname"; then
		pvcreate "$D"
		vgcreate "$VGname" "$D" # --physicalextentsize=8k
		[ -n "$thinpercent" ] && lvcreate -l "$thinpercent"%FREE --thinpool thin scratch
	fi
	vgchange -ay
}

# create vg
# not in /tmp, because that is a limited-size tmpfs
[ "$LB_DIST" = "rhel6.0" ] && { modprobe dm-mod; sed -i "s/use_lvmetad/use_lvmetad=1 #/" /etc/lvm/lvm.conf; }
mkdir -p /run/lvm && /sbin/lvmetad
if [ -z "$blockdevice" ]; then
	if [ -n "$ramdisk" ]; then
		echo "Creating LV from ram disk"
		modprobe brd rd_nr=1 rd_size="$(numfmt --from=auto --to-unit=K "$ramdisk")"
		create_vg scratch /dev/ram0 blockdevice
	else
		echo "Creating LV from loopback file"
		modprobe loop
		create_vg scratch /var/lib/my-vg file
	fi
else
	echo "Creating LV from passed in blockdevice"
	create_vg scratch /dev/sda blockdevice
fi
